config/routes.rb
RubyBlog::Application.routes.draw do
  resources :resources

  resources :reviews

  resources :articles

  resources :posts

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :ok }
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :review_author %><br />
    <%= f.text_field :review_author %>
  </div>
  <div class="field">
    <%= f.label :review_date %><br />
    <%= f.text_field :review_date %>
  </div>
  <div class="field">
    <%= f.label :review_title %><br />
    <%= f.text_field :review_title %>
  </div>
  <div class="field">
    <%= f.label :product_name %><br />
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :review_content %><br />
    <%= f.text_field :review_content %>
  </div>
  <div class="field">
    <%= f.label :review_meta_keywords %><br />
    <%= f.text_field :review_meta_keywords %>
  </div>
  <div class="field">
    <%= f.label :review_meta_description %><br />
    <%= f.text_field :review_meta_description %>
  </div>
  <div class="field">
    <%= f.label :review_url %><br />
    <%= f.text_field :review_url %>
  </div>
  <div class="field">
    <%= f.label :review_external_url %><br />
    <%= f.text_field :review_external_url %>
  </div>
  <div class="field">
    <%= f.label :review_external_org %><br />
    <%= f.text_field :review_external_org %>
  </div>
  <div class="field">
    <%= f.label :review_pic_url %><br />
    <%= f.text_field :review_pic_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Review author</th>
    <th>Review date</th>
    <th>Review title</th>
    <th>Product name</th>
    <th>Review content</th>
    <th>Review meta keywords</th>
    <th>Review meta description</th>
    <th>Review url</th>
    <th>Review external url</th>
    <th>Review external org</th>
    <th>Review pic url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.review_author %></td>
    <td><%= review.review_date %></td>
    <td><%= review.review_title %></td>
    <td><%= review.product_name %></td>
    <td><%= review.review_content %></td>
    <td><%= review.review_meta_keywords %></td>
    <td><%= review.review_meta_description %></td>
    <td><%= review.review_url %></td>
    <td><%= review.review_external_url %></td>
    <td><%= review.review_external_org %></td>
    <td><%= review.review_pic_url %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Review author:</b>
  <%= @review.review_author %>
</p>

<p>
  <b>Review date:</b>
  <%= @review.review_date %>
</p>

<p>
  <b>Review title:</b>
  <%= @review.review_title %>
</p>

<p>
  <b>Product name:</b>
  <%= @review.product_name %>
</p>

<p>
  <b>Review content:</b>
  <%= @review.review_content %>
</p>

<p>
  <b>Review meta keywords:</b>
  <%= @review.review_meta_keywords %>
</p>

<p>
  <b>Review meta description:</b>
  <%= @review.review_meta_description %>
</p>

<p>
  <b>Review url:</b>
  <%= @review.review_url %>
</p>

<p>
  <b>Review external url:</b>
  <%= @review.review_external_url %>
</p>

<p>
  <b>Review external org:</b>
  <%= @review.review_external_org %>
</p>

<p>
  <b>Review pic url:</b>
  <%= @review.review_pic_url %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>